Repository WalterGonzalez33/hotelSolDeSanJavierFront, pull requests merged in 2024-12, with the labels that each got.

#1 Feature/admin/edit reservation
  babel.config.js
  package-lock.json
  package.json
  src/components/adminComponents/FormReservationEdit/FormReservationEdit.jsx
  src/components/adminComponents/ModalAdmin/ModalAdmin.jsx
  src/components/adminComponents/ReservationContainer/ReservationContainer.jsx
  src/components/adminComponents/ReservationRow/ReservationRow.jsx
  src/utils/validateDate.js
  vite.config.js
Labels: enhancement

#2 feature/DeleteReservationsAdmin
  src/components/adminComponents/ReservationContainer/ReservationContainer.jsx
  src/components/adminComponents/ReservationRow/ReservationRow.jsx
  src/components/pages/Admin/Admin.jsx
Labels: enhancement

#3 Feature/admin/integrate tokens
  src/App.jsx
  src/components/BtnLogin/BtnLogin.jsx
  src/components/FilterRoomsContainer/FilterRoomsContainer.jsx
  src/components/adminComponents/FormReservation/FormReservation.jsx
  src/components/adminComponents/FormReservationEdit/FormReservationEdit.jsx
  src/components/adminComponents/FormrRoom/FormRoom.jsx
  src/components/common/Navbar/NavbarComponent.jsx
  src/components/pages/Login/Login.jsx
  src/components/pages/ReservationForm.jsx
  src/components/pages/Rooms.jsx
  src/hooks/useFetch.jsx
  src/utils/customAlert.js
  src/utils/queris.js
  src/utils/requests.js
Labels: enhancement

#4 feature/editHabitaciones
  src/components/adminComponents/CardAdminRoom/CardAdminRoom.jsx
  src/components/adminComponents/FormRoomEdit/FormRoomEdit.jsx
  src/components/adminComponents/ModalAdmin/ModalAdmin.jsx
  src/components/adminComponents/RowRoom/RowRoom.jsx
  src/components/routes/AdminRoute.jsx
Labels: enhancement

#5 Feature/new improve
  src/App.jsx
  src/components/adminComponents/RowRoom/RowRoom.jsx
  src/components/common/Footer/Footer.jsx
  src/components/common/NavLink/NavLink.jsx
  src/components/common/Navbar/NavbarComponent.jsx
  src/components/pages/Contactos.jsx
  src/components/pages/Gallery.jsx
  src/components/pages/Rooms.jsx
  src/styles/global.css
Labels: enhancement

#17 Fix/tamaño boton
  README.md
  src/components/pages/Login/Login.css
  src/components/pages/Login/Login.jsx
  src/components/pages/QuienesSomos.jsx
  src/components/pages/Register/Register.jsx
  src/utils/requests.js
Labels: bug

#18 fix/reservation
  src/components/pages/ReservationForm.jsx
  src/styles/global.css
  src/utils/customAlert.js
Labels: bug, enhancement

#19 fix/inputs and links
  src/components/common/Footer/Footer.jsx
  src/components/pages/Contactos.jsx
  src/components/pages/Login/Login.jsx
Labels: bug

#20 feature/error404
  src/App.jsx
  src/assets/error404.svg
  src/components/indexComponents/AcercaDeNosotros.jsx
  src/components/indexComponents/Experiencias.jsx
  src/components/indexComponents/Promociones.jsx
  src/components/pages/Error404/Error404.jsx
  src/components/pages/Error404/Error404.module.css
Labels: bug, enhancement

#21 merge for production
  src/App.jsx
  src/assets/error404.svg
  src/components/common/Footer/Footer.jsx
  src/components/indexComponents/AcercaDeNosotros.jsx
  src/components/indexComponents/Experiencias.jsx
  src/components/indexComponents/Promociones.jsx
  src/components/pages/Contactos.jsx
  src/components/pages/Error404/Error404.jsx
  src/components/pages/Error404/Error404.module.css
  src/components/pages/Login/Login.css
  src/components/pages/Login/Login.jsx
  src/components/pages/ReservationForm.jsx
  src/styles/global.css
  src/utils/customAlert.js
Labels: bug, documentation, enhancement
